### PR TITLE
upgrade to babel 6

### PR DESCRIPTION
**Pull request by cwalv**
#17

### CODE REVIEW

**Comment by cwalv** [comment]
With this PR, I was able to build [react-select](https://github.com/JedWatson/react-select) without the [broken ES6 module output](https://github.com/JedWatson/react-select/blob/master/lib/Select.js#L950), so it can be consumed from other babel 6 projects that use ES6 module imports

**Comment by gor181** [comment]
Is this going to be merged ? Would like to use it.

**Comment by loris** [comment]
👍

**Comment by chadfennell** [comment]
Lovely - just tested this on a project and am getting clean builds. Babel 6 :smile_cat:  :100:  :smile_cat:

**Review by FDiskas — APPROVED** [review]

**Comment by FDiskas** [comment]
Project dead?

**Pull request closed without merging**
