### PR TITLE
Include scss option

### PR DESCRIPTION
**Pull request by gojohnnygo**
This PR looks for scss build option (in addition to less) in the `taskConfig` file.

scss option is also available to the example build.

### CODE REVIEW

**Comment by gojohnnygo** [comment]
Any feedback on this PR? Thanks!

**Comment by YeahButHats** [comment]
I'd like to see this feature; I had a PR ready myself until I saw this.

**Comment by rubybrowncoat** [comment]
Any news on this?

**Comment by JedWatson** [comment]
Sorry for the delay - this looks great @gojohnnygo, any chance you can rebase so I can merge it?

**Pull request closed without merging**
